name: Test reference branch

on:
  workflow_call:
  push:
  release:
    types: [published]

jobs:
  test-ref-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default repository
        uses: actions/checkout@v5
        with:
          fetch-tags: 'true'

      - name: Reference branch
        id: ref-branch
        uses: aidc-toolkit/.github/actions/ref-branch@v0.9

      - name: Show branch
        run: |
          echo "branch=${{ steps.ref-branch.outputs.branch }}"
          echo "branch_name=${{ steps.ref-branch.outputs.branch_name }}"
